### ISSUE TITLE
How Does Batch Normalization Help Optimization | Bengxy

### ISSUE THREAD

**Issue by bengxy** [bengxy/blog-comment-gittalk#40]
http://localhost:4000/posts/450074ea/

**Comment by leeyifu** [comment]
What's this, bro?

**Comment by bengxy** [comment]
> What's this, bro?

这个： http://blog.bengxy.com/posts/450074ea/

**Comment by leeyifu** [comment]
我意思是你搞这个自己给自己提issue干嘛啊？

**Comment by bengxy** [comment]
> 我意思是你搞这个自己给自己提issue干嘛啊？

这个issue是文章最底部的gitalk评论系统自动生成的，用github的issue做评论页。
